# -*- coding: utf-8 -*-
"""Tracker for current  100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihckUvlIc6qlcCSPaPTLcfOFTTaZB16H

According to https://companiesmarketcap.com/usa/largest-companies-in-the-usa-by-market-cap/
"""

import pandas as pd
import yfinance as yf

stock = yf.Ticker("AAPL")
info = stock.info

print(info)

tickers = ['MSFT', 'AAPL', 'NVDA', 'AMZN', 'GOOGL', 'META', 'BRK.B', 'TSLA', 'AVGO', 'LLY',
           'V', 'JPM', 'JNJ', 'WMT', 'UNH', 'PG', 'MA', 'XOM', 'HD', 'ORCL',
           'CVX', 'ABBV', 'MRK', 'PFE', 'KO', 'PEP', 'BAC', 'ADBE', 'CMCSA', 'COST',
           'NFLX', 'CSCO', 'CRM', 'TMO', 'ABT', 'INTC', 'MCD', 'NEE', 'ACN', 'TXN',
           'DHR', 'VZ', 'T', 'AMD', 'MDT', 'UNP', 'INTU', 'QCOM', 'AMGN', 'BMY',
           'SBUX', 'CHTR', 'CAT', 'LMT', 'GE', 'CVS', 'RTX', 'AXP', 'BA', 'LIN',
           'BKNG', 'ANTM', 'GM', 'NOC', 'GILD', 'TGT', 'F', 'MMM', 'CL', 'MDLZ',
           'GD', 'SO', 'D', 'AMT', 'CI', 'ETN', 'SPGI', 'ITW', 'CCI', 'WM',
           'ADP', 'PSA', 'CB', 'SHW', 'DOW', 'PNC', 'MMC', 'BLK', 'COF', 'REGN',
           'PGR', 'PSX', 'ES', 'AIG', 'COP', 'DUK', 'VLO', 'KHC', 'BIIB', 'PYPL']

data = []

for ticker in tickers:
    try:
        stock = yf.Ticker(ticker)
        info = stock.info

        row = {'Symbol': ticker,
            'Company': info.get('longName'),
            'Recommendation': info.get('recommendationKey'),
            'Market Cap': info.get('marketCap'),
            'Price': info.get('currentPrice'),
            'Volume': info.get('volume'),
            'P/E Ratio': info.get('trailingPE'),
            '5-Year Dividend Yield': info.get('fiveYearAvgDividendYield'),
            'Revenue Per Share': info.get('revenuePerShare'),
            'EBITDA Margin': info.get('ebitdaMargins'),
            'Profit Margin': info.get('profitMargins'),
            'Gross Margin': info.get('grossMargins'),
            'Current Ratio': info.get('currentRatio'),
            'Debt To Equity': info.get('debtToEquity') }

        data.append(row)

    except Exception as e:
        print(f"Failed for {ticker}: {e}")

df = pd.DataFrame(data)

df['Market Cap'] = df['Market Cap'].astype('Int64')
df['Volume'] = df['Volume'].astype('Int64')

df

df.to_csv("stock_data.csv", index=False)